version: "{branch}-{build}"
image: Visual Studio 2017
pull_requests:
  do_not_increment_build_number: true
skip_branch_with_pr: true
branches:
  only:
  - master
platform:
- x64
shallow_clone: true
init:
- ps: >-
    echo $env:PLATFORM

    if ($env:PLATFORM -eq "x86") {
      $Env:JAVA_HOME = "C:\Program Files (x86)\Java\jdk1.8.0"
      echo "32 Bit"
    }

    else {
      $Env:JAVA_HOME = "C:\Program Files\Java\jdk1.8.0"
      echo "64 bit"
    }
install:
- ps: ./gradlew clean
cache: C:\Users\appveyor\.gradle
build_script:
- ps: >-
    echo $env:JAVA_HOME

    ./gradlew build --continue

    if ($lastexitcode -ne 0) {
        $errorstore = $errorMessage
        ./gradlew --stop
        throw ("Exec: " + $errorMessage)
    }

    ./gradlew --stop
test: off
