name: Gazebo

on: [pull_request, push]

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    container: wpilib/gazebo-ubuntu:18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build Gazebo plugins
        run: ./gradlew simulation:frc_gazebo_plugins:build -PbuildServer -PmakeSim
      - name: Build Gazebo HALSIM plugin
        run: ./gradlew simulation:halsim_gazebo:build -PbuildServer -PmakeSim
